version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _offline
  timestamp: 1775727462
layout:
  navigation: {  }
  /slideshow/: {  }
  /hero/: {  }
  /topa/: {  }
  /topb/: {  }
  /topc/: {  }
  /topd/: {  }
  /above/: {  }
  /container-main/:
    -
      -
        'sidebar 25': {  }
      -
        'mainbar 50':
          -
            - system-messages-4539
          -
            - system-content-3237
      -
        'aside 25': {  }
  /below/: {  }
  /bottoma/: {  }
  /bottomb/: {  }
  /bottomc/: {  }
  /bottomd/: {  }
  /extended/: {  }
  footer: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - children
        - attributes
  slideshow:
    type: section
    attributes:
      boxed: '2'
  hero:
    type: section
    attributes:
      class: ''
      boxed: ''
      variations: jl-section
  topa:
    type: section
    attributes:
      boxed: ''
      variations: jl-section
  topb:
    type: section
    attributes:
      boxed: ''
      variations: jl-section
  topc:
    type: section
    attributes:
      boxed: ''
      variations: jl-section
  topd:
    type: section
    attributes:
      boxed: ''
      variations: jl-section
  above:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  mainbar:
    type: section
  container-main:
    attributes:
      boxed: ''
      class: jl-section
      extra: {  }
  below:
    type: section
    attributes:
      boxed: ''
  bottoma:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: jl-section
  bottomb:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: jl-section
  bottomc:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: jl-section
  bottomd:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: jl-section
  extended:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: jl-section
  footer:
    inherit:
      outline: default
      include:
        - children
        - attributes
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    attributes:
      position: g-offcanvas-left
      class: ''
      extra: {  }
      swipe: '0'
      css3animation: '1'
