<?php
defined('_JEXEC') or die;
return array (
  'PLG_MULTIFACTORAUTH_TOTP' => 'Multi-factor Authentication - Verification Code',
  'PLG_MULTIFACTORAUTH_TOTP_XML_DESCRIPTION' => 'Multi-factor Authentication for your site\'s users using six digit verification codes generated by an authenticator app (Google Authenticator, Authy, LastPass Authenticator, etc), a password manager (1Password, BitWarden, Keeper, KeePassXC, Strongbox, etc) or, in some cases, their browser.',
);
