name: _body_only
timestamp: 1775727463
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1775727462
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-3514: 'System Messages'
  content:
    system-content-4202: 'Page Content'
inherit: {  }
